# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:mac)

platform :mac do

  before_all do
    setup_travis
  end

  desc "Build TogglCore"
  lane :build do
    gym(scheme: "TogglCore")
  end

  desc "Run Test of TogglCore"
  lane :test do
    scan(scheme: "TogglCore", workspace: "DesktopWorksapce.xcworkspace")
  end
end
